
------ 1. ROLES ------

INSERT INTO roles (nombre) VALUES ('ROLE_VENDEDOR');
INSERT INTO roles (nombre) VALUES ('ROLE_COMPRADOR');


------ 2. USUARIOS (VENDEDORES) ------

INSERT INTO usuarios (email, password, nombre, direccion, telefono)
VALUES ('vendedor1@marketplace.com', '123456', 'Joyería Central', 'Av. Corrientes 1234', '1122334455');

INSERT INTO usuarios (email, password, nombre, direccion, telefono)
VALUES ('vendedor2@marketplace.com', '123456', 'Platería Moderna', 'Calle Florida 567', '1199887766');


------ 3. ASIGNACIÓN DE ROLES (Tabla Intermedia) ------

INSERT INTO usuario_rol (id_usuario, id_rol)
SELECT (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'),
       (SELECT id FROM roles WHERE nombre = 'ROLE_VENDEDOR');

INSERT INTO usuario_rol (id_usuario, id_rol)
SELECT (SELECT id FROM usuarios WHERE email = 'vendedor2@marketplace.com'),
       (SELECT id FROM roles WHERE nombre = 'ROLE_VENDEDOR');


------ 4. CATEGORÍAS ------

INSERT INTO categorias (nombre, slug, descripcion, publicado)
VALUES ('Joyería', 'joyeria', 'Aros, pulseras, collares y anillos', true);

INSERT INTO categorias (nombre, slug, descripcion, publicado)
VALUES ('Relojes', 'relojes', 'Relojes clásicos y smartwatches', true);

INSERT INTO categorias (nombre, slug, descripcion, publicado)
VALUES ('Lingotes', 'lingotes', 'Lingotes de oro y plata', true);

INSERT INTO categorias (nombre, slug, descripcion, publicado)
VALUES ('Edición Limitada', 'edicion-limitada', 'Piezas exclusivas', true);


------ 5. PRODUCTOS, IMÁGENES, MATERIALES Y CARACTERÍSTICAS ------
-- Migrados desde src/data/productos.js del front (19 productos con
-- detalle completo: descripción, badge, specs, esencia y características).

-- =========================================================
-- PRODUCTOS con detalle completo, imágenes, specs, esencia y
-- características (migrados del mock del front en su totalidad)
-- =========================================================

-- MATERIALES (para filtrado)
INSERT INTO materiales (name) SELECT 'Plata 925' WHERE NOT EXISTS (SELECT 1 FROM materiales WHERE name = 'Plata 925');
INSERT INTO materiales (name) SELECT 'Oro Amarillo 18k' WHERE NOT EXISTS (SELECT 1 FROM materiales WHERE name = 'Oro Amarillo 18k');
INSERT INTO materiales (name) SELECT 'Oro Blanco' WHERE NOT EXISTS (SELECT 1 FROM materiales WHERE name = 'Oro Blanco');
INSERT INTO materiales (name) SELECT 'Cuero' WHERE NOT EXISTS (SELECT 1 FROM materiales WHERE name = 'Cuero');
INSERT INTO materiales (name) SELECT 'Acero inoxidable' WHERE NOT EXISTS (SELECT 1 FROM materiales WHERE name = 'Acero inoxidable');
INSERT INTO materiales (name) SELECT 'Silicona' WHERE NOT EXISTS (SELECT 1 FROM materiales WHERE name = 'Silicona');
INSERT INTO materiales (name) SELECT 'Oro Laminado' WHERE NOT EXISTS (SELECT 1 FROM materiales WHERE name = 'Oro Laminado');

-- PRODUCTOS + DETALLE + IMÁGENES + MATERIAL + CARACTERÍSTICAS
-- Aros Aura Pearl (joyeria / Aros)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Aros Aura Pearl', 'Los Aros Aura Pearl destacan por su diseño delicado y sofisticado, combinando líneas modernas con un brillo sutil que realza cualquier estilo. Su acabado refinado y detalles cuidadosamente trabajados los convierten en una pieza versátil, ideal tanto para ocasiones especiales como para el uso diario. Diseñados para aportar elegancia y distinción en cada momento.', 90000, 10, 'FISICO', 'Aros', 'EXCLUSIVIDAD', '12 gramos', 'Autenticado por GIA', 'Aleación premium con baño de rodio y cristales de alta calidad', 'Cada detalle de los Aros Aura Pearl fue creado para transmitir feminidad y sofisticación. Una joya atemporal que complementa cualquier look con un toque de brillo discreto y refinado.', (SELECT id FROM categorias WHERE slug = 'joyeria'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros aura/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros aura/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros aura/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros aura/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Plata 925'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Brillo Inigualable', 'Cada cristal ha sido cuidadosamente seleccionado para ofrecer una luminosidad excepcional.', (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Atemporal', 'Su forma clásica en lágrima garantiza elegancia que nunca pasa de moda.', (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Comodidad Superior', 'Livianos y ergonómicos para acompañarte durante todo el día.', (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Acabado Premium', 'Materiales de alta calidad que aseguran durabilidad y sofisticación.', (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));

-- Aros Alba (joyeria / Aros)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Aros Alba', 'Los Aros Alba combinan un diseño contemporáneo con detalles inspirados en la elegancia clásica. Su forma distintiva y acabado brillante crean una pieza versátil capaz de realzar tanto estilos casuales como sofisticados. Pensados para quienes buscan accesorios con personalidad y encanto.', 110000, 10, 'FISICO', 'Aros', NULL, '10 gramos', 'Autenticado por GIA', 'Aleación premium bañada en oro con cristales engarzados', 'Los Aros Alba combinan delicadeza y glamour en un diseño de inspiración clásica. Sus detalles brillantes y su acabado dorado crean una pieza refinada que realza cualquier look, desde eventos especiales hasta ocasiones cotidianas.', (SELECT id FROM categorias WHERE slug = 'joyeria'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros alba/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Aros Alba' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros alba/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Alba' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros alba/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Alba' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros alba/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Alba' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Aros Alba' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Oro Amarillo 18k'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Exclusivo', 'Inspirado en la belleza de las joyas clásicas de alta gama.', (SELECT id FROM productos WHERE nombre = 'Aros Alba' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Brillo Sofisticado', 'Los cristales aportan destellos elegantes desde cualquier ángulo.', (SELECT id FROM productos WHERE nombre = 'Aros Alba' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Acabado Dorado', 'Un tono cálido y refinado que complementa cualquier estilo.', (SELECT id FROM productos WHERE nombre = 'Aros Alba' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Durabilidad Garantizada', 'Fabricados para conservar su brillo y belleza con el paso del tiempo.', (SELECT id FROM productos WHERE nombre = 'Aros Alba' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));

-- Aros Éter (joyeria / Aros)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Aros Éter', 'Los Aros Éter reflejan la delicadeza de la naturaleza a través de un diseño inspirado en formas orgánicas y detalles luminosos. Su estética elegante aporta frescura y sofisticación, convirtiéndolos en una pieza única para quienes valoran la exclusividad.', 100000, 10, 'FISICO', 'Aros', NULL, '9 gramos', 'Autenticado por GIA', 'Oro Blanco', 'Los Aros Éter presentan una silueta moderna y minimalista que combina líneas suaves con un acabado dorado brillante. Su diseño versátil los convierte en el complemento perfecto para cualquier ocasión.', (SELECT id FROM categorias WHERE slug = 'joyeria'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros eter/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Aros Éter' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros eter/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Éter' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros eter/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Éter' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros eter/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Éter' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Aros Éter' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Oro Blanco'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Estilo Moderno', 'Diseño contemporáneo inspirado en las tendencias más exclusivas.', (SELECT id FROM productos WHERE nombre = 'Aros Éter' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Ligereza Perfecta', 'Pensados para brindar comodidad durante largas jornadas.', (SELECT id FROM productos WHERE nombre = 'Aros Éter' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Acabado Refinado', 'Superficie pulida que refleja la luz con sutileza.', (SELECT id FROM productos WHERE nombre = 'Aros Éter' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Versatilidad Total', 'Ideales tanto para eventos formales como para uso diario.', (SELECT id FROM productos WHERE nombre = 'Aros Éter' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));

-- Aros Ambar (joyeria / Aros)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Aros Ambar', 'Los Aros Ámbar cautivan con su diseño inspirado en la naturaleza. Sus delicadas formas de hojas cubiertas de cristales generan un efecto brillante y elegante que aporta sofisticación a cualquier conjunto.', 140000, 10, 'FISICO', 'Aros', 'EXCLUSIVIDAD', '14 gramos', 'Autenticado por GIA', 'Aleación premium bañada en oro con cristales microengarzados', 'Los Aros Ámbar cautivan con su diseño inspirado en la naturaleza. Sus delicadas formas de hojas cubiertas de cristales generan un efecto brillante y elegante que aporta sofisticación a cualquier conjunto.', (SELECT id FROM categorias WHERE slug = 'joyeria'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aro ambar/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aro ambar/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aro ambar/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aro ambar/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Oro Blanco'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Inspiración Natural', 'Un diseño que refleja la belleza y armonía de las hojas.', (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Máximo Brillo', 'Cristales cuidadosamente colocados para una luminosidad excepcional.', (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Acabado Artesanal', 'Detalles refinados que destacan la calidad de la pieza.', (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Exclusividad Garantizada', 'Una joya creada para quienes buscan distinguirse.', (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Aros' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));

-- Anillo Eternity (joyeria / Anillos)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Anillo Eternity', 'El Anillo Eternity simboliza elegancia, compromiso y sofisticación. Su diseño delicado y brillante resalta la belleza de cada detalle, convirtiéndolo en una pieza ideal para celebrar momentos especiales o complementar un estilo refinado.', 80000, 10, 'FISICO', 'Anillos', NULL, '6 gramos', 'Autenticado por GIA', 'Plata esterlina con cristales premium', 'El Anillo Eternity simboliza elegancia y eternidad a través de una línea continua de brillantes cristales. Su diseño refinado lo convierte en una pieza ideal para celebrar momentos especiales o complementar cualquier colección de joyería.', (SELECT id FROM categorias WHERE slug = 'joyeria'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/anillo eternity/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Anillo Eternity' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/anillo eternity/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Anillo Eternity' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/anillo eternity/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Anillo Eternity' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Anillo Eternity' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Plata 925'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Simbolismo Eterno', 'Representa la unión, el compromiso y la belleza sin fin.', (SELECT id FROM productos WHERE nombre = 'Anillo Eternity' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Brillo Continuo', 'Cristales distribuidos uniformemente para una apariencia impecable.', (SELECT id FROM productos WHERE nombre = 'Anillo Eternity' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Refinado', 'Una pieza delicada y sofisticada para cualquier ocasión.', (SELECT id FROM productos WHERE nombre = 'Anillo Eternity' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Calidad Premium', 'Materiales seleccionados para garantizar resistencia y durabilidad.', (SELECT id FROM productos WHERE nombre = 'Anillo Eternity' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));

-- Anillo Vittoria (joyeria / Anillos)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Anillo Vittoria', 'El Anillo Vittoria es una pieza que combina lujo y delicadeza en un diseño cautivador. Su piedra central y acabado refinado crean una joya elegante que destaca por su presencia y sofisticación.', 130000, 10, 'FISICO', 'Anillos', NULL, '5 gramos', 'Autenticado por GIA', 'Aleación premium bañada en oro con cristales de alta calidad', 'El Anillo Vittoria combina delicadeza y modernidad en un diseño abierto con detalles brillantes. Su estilo elegante y femenino lo convierte en una pieza ideal para quienes buscan sofisticación con un toque contemporáneo.', (SELECT id FROM categorias WHERE slug = 'joyeria'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/anillo victoria/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Anillo Vittoria' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/anillo victoria/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Anillo Vittoria' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/anillo victoria/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Anillo Vittoria' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Anillo Vittoria' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Oro Blanco'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Elegancia Contemporánea', 'Una propuesta moderna que conserva la esencia de la joyería clásica.', (SELECT id FROM productos WHERE nombre = 'Anillo Vittoria' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Brillo Delicado', 'Los detalles engarzados aportan luminosidad sutil y refinada.', (SELECT id FROM productos WHERE nombre = 'Anillo Vittoria' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Versátil', 'Perfecto para combinar con otras piezas o lucir individualmente.', (SELECT id FROM productos WHERE nombre = 'Anillo Vittoria' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Acabado Premium', 'Fabricado con materiales resistentes y de excelente calidad.', (SELECT id FROM productos WHERE nombre = 'Anillo Vittoria' AND subcategoria = 'Anillos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));

-- Collar Heaven (joyeria / Collares)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Collar Heaven', 'El Collar Heaven combina delicadeza y brillo en una composición elegante inspirada en la belleza celestial. Sus detalles cuidadosamente distribuidos aportan armonía y sofisticación, convirtiéndolo en una pieza ideal para ocasiones memorables.', 170000, 10, 'FISICO', 'Collares', NULL, '15 gramos', 'Autenticado por GIA', 'Oro Blanco', 'El Collar Heaven destaca por su colgante orgánico y elegante que enmarca una delicada perla central. Una joya diseñada para transmitir sofisticación, armonía y estilo en cada detalle.', (SELECT id FROM categorias WHERE slug = 'joyeria'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/collar heaven/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Collar Heaven' AND subcategoria = 'Collares' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/collar heaven/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Collar Heaven' AND subcategoria = 'Collares' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/collar heaven/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Collar Heaven' AND subcategoria = 'Collares' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Collar Heaven' AND subcategoria = 'Collares' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Oro Blanco'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Inspiración Orgánica', 'Diseño inspirado en las formas naturales y fluidas.', (SELECT id FROM productos WHERE nombre = 'Collar Heaven' AND subcategoria = 'Collares' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Delicadeza Atemporal', 'Una pieza que aporta sofisticación sin excesos.', (SELECT id FROM productos WHERE nombre = 'Collar Heaven' AND subcategoria = 'Collares' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Materiales Premium', 'Acabados de alta calidad para una apariencia impecable.', (SELECT id FROM productos WHERE nombre = 'Collar Heaven' AND subcategoria = 'Collares' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Versatilidad Elegante', 'Ideal para complementar tanto looks casuales como formales.', (SELECT id FROM productos WHERE nombre = 'Collar Heaven' AND subcategoria = 'Collares' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));

-- Pulsera Firenze (joyeria / Pulseras)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Pulsera Firenze', 'La Pulsera Firenze combina sofisticación y carácter en una pieza diseñada para destacar. Sus detalles ornamentales y su acabado brillante crean un accesorio elegante que aporta personalidad y distinción a cualquier conjunto.', 180000, 10, 'FISICO', 'Pulseras', NULL, '18 gramos', 'Autenticado por GIA', 'Aleación premium con baño de oro y detalles nacarados', 'La Pulsera Firenze fusiona modernidad y sofisticación mediante un diseño fluido y elegante. Sus detalles nacarados y acabados dorados crean una pieza única que destaca por su exclusividad.', (SELECT id FROM categorias WHERE slug = 'joyeria'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/pulsera firenze/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Pulsera Firenze' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/pulsera firenze/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Pulsera Firenze' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/pulsera firenze/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Pulsera Firenze' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Pulsera Firenze' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Oro Blanco'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Exclusivo', 'Inspirado en la elegancia artística de la alta joyería europea.', (SELECT id FROM productos WHERE nombre = 'Pulsera Firenze' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Acabado Nacarado', 'Detalles que aportan luminosidad y sofisticación.', (SELECT id FROM productos WHERE nombre = 'Pulsera Firenze' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Comodidad Garantizada', 'Diseño ergonómico para un ajuste cómodo y seguro.', (SELECT id FROM productos WHERE nombre = 'Pulsera Firenze' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Distinción Atemporal', 'Una pieza creada para destacar en cualquier ocasión.', (SELECT id FROM productos WHERE nombre = 'Pulsera Firenze' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));

-- Pulsera Siena (joyeria / Pulseras)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Pulsera Siena', 'La Pulsera Siena destaca por su diseño minimalista y elegante, ideal para quienes prefieren la sofisticación discreta. Su delicada estructura aporta luminosidad y armonía, convirtiéndola en el complemento perfecto para cualquier ocasión.', 110000, 10, 'FISICO', 'Pulseras', NULL, '16 gramos', 'Autenticado por GIA', 'Plata premium con cristales de alta calidad', 'La Pulsera Siena refleja lujo y delicadeza en un diseño minimalista adornado con brillantes detalles. Su estilo refinado la convierte en un accesorio imprescindible para quienes valoran la elegancia discreta.', (SELECT id FROM categorias WHERE slug = 'joyeria'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/pulsera siena/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Pulsera Siena' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/pulsera siena/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Pulsera Siena' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/pulsera siena/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Pulsera Siena' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/pulsera siena/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Pulsera Siena' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Pulsera Siena' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Plata 925'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Brillo Refinado', 'Detalles cuidadosamente trabajados para aportar luminosidad.', (SELECT id FROM productos WHERE nombre = 'Pulsera Siena' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Minimalista', 'Elegancia simple que nunca pierde vigencia.', (SELECT id FROM productos WHERE nombre = 'Pulsera Siena' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Materiales de Calidad', 'Construida con componentes seleccionados por su durabilidad.', (SELECT id FROM productos WHERE nombre = 'Pulsera Siena' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Estilo Versátil', 'Perfecta para ocasiones especiales o uso cotidiano.', (SELECT id FROM productos WHERE nombre = 'Pulsera Siena' AND subcategoria = 'Pulseras' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'joyeria') ORDER BY id DESC LIMIT 1));

-- Reloj Imperial (relojes / Relojes clásicos)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Reloj Imperial', 'El reloj Imperial combina sofisticación clásica y diseño contemporáneo en una pieza exclusiva. Su esfera negra con detalles dorados y numeración romana aporta presencia y distinción, mientras que la correa de cuero texturizado brinda comodidad y un acabado refinado. Diseñado para quienes valoran la elegancia atemporal y los detalles de lujo en cada ocasión.', 200000, 10, 'FISICO', 'Relojes clásicos', 'EXCLUSIVIDAD', '55 Gramos', 'Autenticado por GIA', 'Cuero premium', 'Cada detalle del reloj Imperial fue diseñado para reflejar sofisticación, precisión y carácter. Una pieza atemporal que combina materiales premium, acabados refinados y un estilo pensado para destacar en cualquier momento.', (SELECT id FROM categorias WHERE slug = 'relojes'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj imperial/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj imperial/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj imperial/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj imperial/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Cuero'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Atemporal', 'Una pieza creada para combinar sofisticación clásica y estilo contemporáneo, ideal para cualquier ocasión.', (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Comodidad Superior', 'Su diseño ergonómico y liviano brinda una experiencia cómoda para el uso diario.', (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Materiales Premium', 'Fabricado con acero inoxidable de alta calidad y correa de cuero texturizado para un acabado refinado y duradero.', (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Durabilidad Garantizada', 'Cristal resistente y materiales seleccionados para acompañarte con estilo a lo largo del tiempo.', (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));

-- Reloj Chronos (relojes / Relojes clásicos)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Reloj Chronos', 'El Reloj Chronos representa la unión perfecta entre innovación y elegancia. Su diseño contemporáneo y presencia sofisticada lo convierten en un accesorio ideal para quienes buscan destacar con estilo.', 150000, 10, 'FISICO', 'Relojes clásicos', NULL, '140 gramos', 'Autenticado por GIA', 'Acero inoxidable premium', 'El Reloj Chronos combina precisión y sofisticación en un diseño moderno de acero inoxidable. Su esfera oscura y detalles mecánicos visibles reflejan innovación, carácter y elegancia.', (SELECT id FROM categorias WHERE slug = 'relojes'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj chronos/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Reloj Chronos' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj chronos/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Chronos' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj chronos/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Chronos' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj chronos/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Chronos' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Reloj Chronos' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Acero inoxidable'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Precisión Superior', 'Movimiento diseñado para ofrecer un rendimiento confiable.', (SELECT id FROM productos WHERE nombre = 'Reloj Chronos' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Contemporáneo', 'Líneas modernas que transmiten fuerza y sofisticación.', (SELECT id FROM productos WHERE nombre = 'Reloj Chronos' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Materiales Premium', 'Acero inoxidable resistente y de acabado impecable.', (SELECT id FROM productos WHERE nombre = 'Reloj Chronos' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Durabilidad Garantizada', 'Preparado para acompañarte durante años.', (SELECT id FROM productos WHERE nombre = 'Reloj Chronos' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));

-- Reloj Monaco (relojes / Smartwatches)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Reloj Monaco', 'El Reloj Monaco fusiona tecnología moderna y diseño minimalista en una pieza elegante y funcional. Su estética contemporánea y acabado refinado lo convierten en el accesorio ideal para quienes buscan innovación sin renunciar al estilo.', 150000, 10, 'FISICO', 'Smartwatches', NULL, '95 gramos', 'Autenticado por GIA', 'Acero inoxidable', 'El Reloj Monaco fusiona tecnología y elegancia con un diseño inspirado en los relojes inteligentes de lujo. Su acabado rosado y correa metálica aportan exclusividad y modernidad.', (SELECT id FROM categorias WHERE slug = 'relojes'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj monaco/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Reloj Monaco' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj monaco/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Monaco' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj monaco/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Monaco' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj monaco/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Monaco' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Reloj Monaco' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Acero inoxidable'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Tecnología y Estilo', 'La combinación perfecta entre funcionalidad y sofisticación.', (SELECT id FROM productos WHERE nombre = 'Reloj Monaco' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Exclusivo', 'Acabado rosado que aporta distinción y modernidad.', (SELECT id FROM productos WHERE nombre = 'Reloj Monaco' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Comodidad Superior', 'Correa adaptable para un ajuste seguro.', (SELECT id FROM productos WHERE nombre = 'Reloj Monaco' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Calidad Premium', 'Materiales seleccionados para garantizar durabilidad.', (SELECT id FROM productos WHERE nombre = 'Reloj Monaco' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));

-- Reloj Noir (relojes / Relojes clásicos)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Reloj Noir', 'El Reloj Noir destaca por su elegancia clásica y su diseño refinado. Su acabado metálico y esfera equilibrada crean una pieza sofisticada que complementa cualquier estilo con distinción y sobriedad.', 180000, 10, 'FISICO', 'Relojes clásicos', NULL, '150 gramos', 'Autenticado por GIA', 'Acero inoxidable', 'El Reloj Noir destaca por su mecanismo visible y estética sofisticada. Una pieza creada para quienes aprecian la ingeniería relojera y el diseño de lujo.', (SELECT id FROM categorias WHERE slug = 'relojes'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj noir/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Reloj Noir' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj noir/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Noir' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj noir/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Noir' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj noir/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Noir' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Reloj Noir' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Acero inoxidable'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Ingeniería Visible', 'Su mecanismo expuesto resalta la complejidad de cada detalle.', (SELECT id FROM productos WHERE nombre = 'Reloj Noir' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Exclusivo', 'Una estética moderna inspirada en la relojería de alta gama.', (SELECT id FROM productos WHERE nombre = 'Reloj Noir' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Máxima Precisión', 'Movimiento confiable y de excelente rendimiento.', (SELECT id FROM productos WHERE nombre = 'Reloj Noir' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Durabilidad Premium', 'Construcción sólida para acompañarte en cada momento.', (SELECT id FROM productos WHERE nombre = 'Reloj Noir' AND subcategoria = 'Relojes clásicos' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));

-- Reloj Tempus (relojes / Smartwatches)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Reloj Tempus', 'El Reloj Tempus combina simplicidad y tecnología en un diseño moderno pensado para el día a día. Su apariencia limpia y funcional lo convierte en un accesorio práctico sin perder elegancia.', 150000, 10, 'FISICO', 'Smartwatches', NULL, '60 gramos', 'Autenticado por GIA', 'Silicona', 'El Reloj Tempus combina tecnología inteligente y diseño moderno en una pieza versátil y elegante. Ideal para quienes buscan funcionalidad sin renunciar al estilo.', (SELECT id FROM categorias WHERE slug = 'relojes'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj tempus/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Reloj Tempus' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj tempus/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Tempus' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj tempus/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Tempus' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj tempus/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Tempus' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Reloj Tempus' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Silicona'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Tecnología Inteligente', 'Funciones modernas para acompañar tu rutina diaria.', (SELECT id FROM productos WHERE nombre = 'Reloj Tempus' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Ergonómico', 'Ligero y cómodo para uso prolongado.', (SELECT id FROM productos WHERE nombre = 'Reloj Tempus' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Estilo Contemporáneo', 'Una estética moderna que combina con cualquier look.', (SELECT id FROM productos WHERE nombre = 'Reloj Tempus' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Rendimiento Confiable', 'Pensado para ofrecer practicidad y durabilidad.', (SELECT id FROM productos WHERE nombre = 'Reloj Tempus' AND subcategoria = 'Smartwatches' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'relojes') ORDER BY id DESC LIMIT 1));

-- Lingote de Oro Laminado (lingotes / Lingotes de Oro)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Lingote de Oro Laminado', 'El Lingote de Oro representa una inversión sólida y una pieza de gran prestigio. Su acabado brillante y presentación impecable reflejan pureza, exclusividad y valor duradero, convirtiéndolo en una elección ideal para coleccionistas e inversionistas.', 2300000, 10, 'FISICO', 'Lingotes de Oro', NULL, '100 gramos', 'Autenticado por GIA', 'Oro Laminado', 'El Lingote de Oro Laminado representa prestigio, exclusividad y valor. Su acabado brillante y su diseño inspirado en lingotes de inversión lo convierten en una pieza ideal para coleccionistas y amantes del lujo.', (SELECT id FROM categorias WHERE slug = 'lingotes'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/lingotes/lingote_oro.jpg', true, (SELECT id FROM productos WHERE nombre = 'Lingote de Oro Laminado' AND subcategoria = 'Lingotes de Oro' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'lingotes') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Lingote de Oro Laminado' AND subcategoria = 'Lingotes de Oro' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'lingotes') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Oro Laminado'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Símbolo de Prestigio', 'Una pieza que representa éxito y exclusividad.', (SELECT id FROM productos WHERE nombre = 'Lingote de Oro Laminado' AND subcategoria = 'Lingotes de Oro' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'lingotes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Acabado Brillante', 'Superficie pulida para una apariencia impecable.', (SELECT id FROM productos WHERE nombre = 'Lingote de Oro Laminado' AND subcategoria = 'Lingotes de Oro' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'lingotes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Inspirado en la Inversión', 'Evoca el lujo y la seguridad de los metales preciosos.', (SELECT id FROM productos WHERE nombre = 'Lingote de Oro Laminado' AND subcategoria = 'Lingotes de Oro' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'lingotes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Calidad Superior', 'Fabricado con materiales cuidadosamente seleccionados.', (SELECT id FROM productos WHERE nombre = 'Lingote de Oro Laminado' AND subcategoria = 'Lingotes de Oro' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'lingotes') ORDER BY id DESC LIMIT 1));

-- Lingote de Plata (lingotes / Lingotes de Plata)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Lingote de Plata', 'El Lingote de Plata combina elegancia, valor y versatilidad en una pieza de gran atractivo. Su acabado refinado y diseño clásico lo convierten en una excelente alternativa para inversión o colección.', 1400000, 10, 'FISICO', 'Lingotes de Plata', NULL, '100 gramos', 'Autenticado por GIA', 'Plata 925', 'El Lingote de Plata combina elegancia y sofisticación en un diseño inspirado en los metales preciosos más valorados. Una pieza exclusiva para coleccionistas y amantes del lujo contemporáneo.', (SELECT id FROM categorias WHERE slug = 'lingotes'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/lingotes/lingote_plata.jpg', true, (SELECT id FROM productos WHERE nombre = 'Lingote de Plata' AND subcategoria = 'Lingotes de Plata' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'lingotes') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Lingote de Plata' AND subcategoria = 'Lingotes de Plata' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'lingotes') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Plata 925'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Distinción Atemporal', 'La plata representa refinamiento y exclusividad.', (SELECT id FROM productos WHERE nombre = 'Lingote de Plata' AND subcategoria = 'Lingotes de Plata' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'lingotes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Acabado Premium', 'Superficie cuidadosamente pulida para resaltar cada detalle.', (SELECT id FROM productos WHERE nombre = 'Lingote de Plata' AND subcategoria = 'Lingotes de Plata' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'lingotes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Inspiración Clásica', 'Diseño elegante basado en lingotes de colección.', (SELECT id FROM productos WHERE nombre = 'Lingote de Plata' AND subcategoria = 'Lingotes de Plata' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'lingotes') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Durabilidad Garantizada', 'Materiales resistentes que preservan su belleza con el tiempo.', (SELECT id FROM productos WHERE nombre = 'Lingote de Plata' AND subcategoria = 'Lingotes de Plata' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'lingotes') ORDER BY id DESC LIMIT 1));

-- Aros Aura Pearl (edicion-limitada / Exclusivo)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Aros Aura Pearl', 'Los Aros Aura Pearl destacan por su diseño delicado y sofisticado, combinando líneas modernas con un brillo sutil que realza cualquier estilo. Su acabado refinado y detalles cuidadosamente trabajados los convierten en una pieza versátil, ideal tanto para ocasiones especiales como para el uso diario. Diseñados para aportar elegancia y distinción en cada momento.', 90000, 10, 'FISICO', 'Exclusivo', 'EXCLUSIVIDAD', '12 gramos', 'Autenticado por GIA', 'Aleación premium con baño de rodio y cristales de alta calidad', 'Cada detalle de los Aros Aura Pearl fue creado para transmitir feminidad y sofisticación. Una joya atemporal que complementa cualquier look con un toque de brillo discreto y refinado.', (SELECT id FROM categorias WHERE slug = 'edicion-limitada'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros aura/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros aura/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros aura/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aros aura/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Plata 925'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Brillo Inigualable', 'Cada cristal ha sido cuidadosamente seleccionado para ofrecer una luminosidad excepcional.', (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Atemporal', 'Su forma clásica en lágrima garantiza elegancia que nunca pasa de moda.', (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Comodidad Superior', 'Livianos y ergonómicos para acompañarte durante todo el día.', (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Acabado Premium', 'Materiales de alta calidad que aseguran durabilidad y sofisticación.', (SELECT id FROM productos WHERE nombre = 'Aros Aura Pearl' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));

-- Aros Ambar (edicion-limitada / Exclusivo)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Aros Ambar', 'Los Aros Ámbar cautivan con su diseño inspirado en la naturaleza. Sus delicadas formas de hojas cubiertas de cristales generan un efecto brillante y elegante que aporta sofisticación a cualquier conjunto.', 140000, 10, 'FISICO', 'Exclusivo', 'EXCLUSIVIDAD', '14 gramos', 'Autenticado por GIA', 'Aleación premium bañada en oro con cristales microengarzados', 'Los Aros Ámbar cautivan con su diseño inspirado en la naturaleza. Sus delicadas formas de hojas cubiertas de cristales generan un efecto brillante y elegante que aporta sofisticación a cualquier conjunto.', (SELECT id FROM categorias WHERE slug = 'edicion-limitada'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aro ambar/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aro ambar/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aro ambar/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/joyeria/aro ambar/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Oro Blanco'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Inspiración Natural', 'Un diseño que refleja la belleza y armonía de las hojas.', (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Máximo Brillo', 'Cristales cuidadosamente colocados para una luminosidad excepcional.', (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Acabado Artesanal', 'Detalles refinados que destacan la calidad de la pieza.', (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Exclusividad Garantizada', 'Una joya creada para quienes buscan distinguirse.', (SELECT id FROM productos WHERE nombre = 'Aros Ambar' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));

-- Reloj Imperial (edicion-limitada / Exclusivo)
INSERT INTO productos (nombre, descripcion, precio, stock, tipo, subcategoria, badge, peso, certificacion, composicion_material, esencia, id_categoria, id_vendedor) VALUES ('Reloj Imperial', 'El reloj Imperial combina sofisticación clásica y diseño contemporáneo en una pieza exclusiva. Su esfera negra con detalles dorados y numeración romana aporta presencia y distinción, mientras que la correa de cuero texturizado brinda comodidad y un acabado refinado. Diseñado para quienes valoran la elegancia atemporal y los detalles de lujo en cada ocasión.', 200000, 10, 'FISICO', 'Exclusivo', 'EXCLUSIVIDAD', '55 Gramos', 'Autenticado por GIA', 'Cuero premium', 'Cada detalle del reloj Imperial fue diseñado para reflejar sofisticación, precisión y carácter. Una pieza atemporal que combina materiales premium, acabados refinados y un estilo pensado para destacar en cualquier momento.', (SELECT id FROM categorias WHERE slug = 'edicion-limitada'), (SELECT id FROM usuarios WHERE email = 'vendedor1@marketplace.com'));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj imperial/foto1.jpg', true, (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj imperial/foto2.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj imperial/foto3.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO imagenes (url, es_portada, id_producto) VALUES ('/src/assets/relojes/reloj imperial/foto4.jpg', false, (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO producto_material (id_producto, id_material) VALUES ((SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1), (SELECT id FROM materiales WHERE name = 'Cuero'));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Diseño Atemporal', 'Una pieza creada para combinar sofisticación clásica y estilo contemporáneo, ideal para cualquier ocasión.', (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Comodidad Superior', 'Su diseño ergonómico y liviano brinda una experiencia cómoda para el uso diario.', (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Materiales Premium', 'Fabricado con acero inoxidable de alta calidad y correa de cuero texturizado para un acabado refinado y duradero.', (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
INSERT INTO caracteristicas (titulo, texto, id_producto) VALUES ('Durabilidad Garantizada', 'Cristal resistente y materiales seleccionados para acompañarte con estilo a lo largo del tiempo.', (SELECT id FROM productos WHERE nombre = 'Reloj Imperial' AND subcategoria = 'Exclusivo' AND id_categoria = (SELECT id FROM categorias WHERE slug = 'edicion-limitada') ORDER BY id DESC LIMIT 1));
